name: Build

on:
  push:
    branches:
      - 3.x
  pull_request:

jobs:
  node12:
    name: node v12 - tsc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install node v12
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: install build tools
        run: sudo apt-get install libcairo2-dev libgif-dev libjpeg-dev libpango1.0-dev librsvg2-dev -y
      - name: yarn
        run: yarn install
      - name: config
        run: cp etc/config.example.json etc/config.json
      - name: tsc
        uses: icrawl/action-tsc@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          job-name: tsc
  node14:
    name: node v14 - tsc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install node v14
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: install build tools
        run: sudo apt-get install libcairo2-dev libgif-dev libjpeg-dev libpango1.0-dev librsvg2-dev -y
      - name: yarn
        run: yarn install
      - name: config
        run: cp etc/config.example.json etc/config.json
      - name: tsc
        uses: icrawl/action-tsc@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          job-name: tsc
