name: Lint

on:
  push:
    branches:
      - 3.x
  pull_request:

jobs:
  node12:
    name: node v12 - eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install node v12
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: yarn install
        run: yarn install
      - name: eslint
        uses: icrawl/action-eslint@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          job-name: eslint
  node14:
    name: node v14 - eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install node v14
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: yarn install
        run: yarn install
      - name: eslint
        uses: icrawl/action-eslint@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          job-name: eslint
